_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": autoencoder_val_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": autoencoder_train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": autoencoder_train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": autoencoder_val_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 9
                - 41
                - 50
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 50
                - 55
                - 103
            "3":
                - 2
                - 7
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
